In [100]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns

In [101]:
df = pd.read_csv("https://raw.githubusercontent.com/lovnishverma/datasets/refs/heads/main/dataset-car-price.csv")

In [102]:
df.head(3)

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50

In [103]:
df.isnull().sum()

Unnamed: 0              0
Name                    0
Location                0
Year                    0
Kilometers_Driven       0
Fuel_Type               0
Transmission            0
Owner_Type              0
Mileage                 2
Engine                 36
Power                  36
Seats                  42
New_Price            5195
Price                   0
dtype: int64

In [104]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6019 entries, 0 to 6018
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         6019 non-null   int64
 1   Name               6019 non-null   str
 2   Location           6019 non-null   str
 3   Year               6019 non-null   int64
 4   Kilometers_Driven  6019 non-null   int64
 5   Fuel_Type          6019 non-null   str
 6   Transmission       6019 non-null   str
 7   Owner_Type         6019 non-null   str
 8   Mileage            6017 non-null   str
 9   Engine             5983 non-null   str
 10  Power              5983 non-null   str
 11  Seats              5977 non-null   float64
 12  New_Price          824 non-null    str
 13  Price              6019 non-null   float64
dtypes: float64(2), int64(3), str(9)
memory usage: 658.5 KB

In [105]:
df.describe()

        Unnamed: 0         Year  Kilometers_Driven        Seats        Price
count  6019.000000  6019.000000       6.019000e+03  5977.000000  6019.000000
mean   3009.000000  2013.358199       5.873838e+04     5.278735     9.479468
std    1737.679967     3.269742       9.126884e+04     0.808840    11.187917
min       0.000000  1998.000000       1.710000e+02     0.000000     0.440000
25%    1504.500000  2011.000000       3.400000e+04     5.000000     3.500000
50%    3009.000000  2014.000000       5.300000e+04     5.000000     5.640000
75%    4513.500000  2016.000000       7.300000e+04     5.000000     9.950000
max    6018.000000  2019.000000       6.500000e+06    10.000000   160.000000

In [106]:
df['Mileage'] = df['Mileage'].str.replace(' kmpl', '').str.replace(' km/kg', '').astype(float)

df['Engine'] = df['Engine'].str.replace(' CC', '').astype(float)

df['Power'] = df['Power'].astype(str).str.replace(' bhp', '').replace('null', np.nan).astype(float)

In [107]:
df.drop(['Unnamed: 0', 'Name', 'Location', 'New_Price'], axis=1, inplace=True)

In [108]:
df['Mileage'] = df['Mileage'].fillna(df['Mileage'].median())
df['Engine'] = df['Engine'].fillna(df['Engine'].median())
df['Power'] = df['Power'].fillna(df['Power'].median())
df['Seats'] = df['Seats'].fillna(df['Seats'].median())

In [109]:
df = pd.get_dummies(df, columns=['Fuel_Type', 'Transmission', 'Owner_Type'], drop_first=True)

In [110]:
df.head()

,Year,Kilometers_Driven,Mileage,Engine,Power,Seats,Price,Fuel_Type_Diesel,Fuel_Type_Electric,Fuel_Type_LPG,Fuel_Type_Petrol,Transmission_Manual,Owner_Type_Fourth & Above,Owner_Type_Second,Owner_Type_Third
0,2010,72000,26.60,998.0,58.16,5.0,1.75,False,False,False,False,True,False,False,False
1,2015,41000,19.67,1582.0,126.20,5.0,12.50,True,False,False,False,True,False,False,False
2,2011,46000,18.20,1199.0,88.70,5.0,4.50,False,False,False,True,True,False,False,False
3,2012,87000,20.77,1248.0,88.76,7.0,6.00,True,False,False,False,True,False,False,False
4,2013,40670,15.20,1968.0,140.80,5.0,17.74,True,False,False,False,False,False,True,False

In [111]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6019 entries, 0 to 6018
Data columns (total 15 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Year                       6019 non-null   int64
 1   Kilometers_Driven          6019 non-null   int64
 2   Mileage                    6019 non-null   float64
 3   Engine                     6019 non-null   float64
 4   Power                      6019 non-null   float64
 5   Seats                      6019 non-null   float64
 6   Price                      6019 non-null   float64
 7   Fuel_Type_Diesel           6019 non-null   bool
 8   Fuel_Type_Electric         6019 non-null   bool
 9   Fuel_Type_LPG              6019 non-null   bool
 10  Fuel_Type_Petrol           6019 non-null   bool
 11  Transmission_Manual        6019 non-null   bool
 12  Owner_Type_Fourth & Above  6019 non-null   bool
 13  Owner_Type_Second          6019 non-null   bool
 14  Owner_Type_Third           6019 non-null   bool
dtypes: bool(8), float64(5), int64(2)
memory usage: 376.3 KB

In [112]:
x = df.drop("Price" , axis=1)
y = df["Price"]

In [113]:
from sklearn.model_selection import train_test_split

In [114]:
x_train , x_test , y_train , y_test = train_test_split(x,y , test_size=0.2 , random_state=42)

In [115]:
from sklearn.linear_model import LinearRegression

In [116]:
lr = LinearRegression()
lr.fit(x_train , y_train)

LinearRegression()

In [117]:
lr.score(x_train , y_train)*100 , lr.score(x_test,y_test)*100

(70.3352160739914, 47.43463453508255)

In [118]:
from sklearn.tree import DecisionTreeRegressor

In [119]:
dr = DecisionTreeRegressor()
dr.fit(x_train , y_train)

DecisionTreeRegressor()

In [120]:
dr.score(x_train , y_train)*100 , dr.score(x_test,y_test)*100

(99.99273149999453, 73.37142685164444)

In [121]:
from sklearn.ensemble import RandomForestRegressor

In [122]:
rf = RandomForestRegressor(n_estimators=100, random_state=42)
rf.fit(x_train, y_train)

RandomForestRegressor(random_state=42)

In [123]:
rf.score(x_train , y_train)*100 , rf.score(x_test,y_test)*100

(98.39058286567673, 85.76364833444653)

In [125]:
lr.predict([[2010, 72000, 26.60, 998.0, 58.16, 5.0 , False,False,	False	,False	, True	, False	, False	, False]])

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([-1.55102285])

In [126]:
dr.predict([[2010, 72000, 26.60, 998.0, 58.16, 5.0 , False,False,	False	,False	, True	, False	, False	, False]])

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(

array([1.75])

In [127]:
rf.predict([[2010, 72000, 26.60, 998.0, 58.16, 5.0 , False,False,	False	,False	, True	, False	, False	, False]])

/opt/miniconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

array([1.8347])