### Apriori Algorithm is a basic method used in data analysis to find groups of items that often appear together in large sets of data. It helps to discover useful patterns or rules about how items are related which is particularly valuable in market basket analysis.

#### Like in a grocery store if many customers buy bread and butter together, the store can use this information to place these items closer or create special offers. This helps the store sell more and make customers happy.

## Key Metrics of Apriori Algorithm
#### 1. Support: This metric measures how frequently an item appears in the dataset relative to the total number of transactions. A higher support indicates a more significant presence of the Item-Set in the dataset. Support tells us how often a particular item or combination of items appears in all the transactions like Bread is bought in 20% of all transactions.
#### 2. Confidence: Confidence assesses the likelihood that an item Y is purchased when item X is purchased. It provides insight into the strength of the association between two items. Confidence tells us how often items go together i.e If bread is bought, butter is bought 75% of the time.
#### 3. Lift: Lift evaluates how much more likely two items are to be purchased together compared to being purchased independently. A lift greater than 1 suggests a strong positive association. Lift shows how strong the connection is between items. Like Bread and butter are much more likely to be bought together than by chance.

## Lets import libraries first

In [26]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

## Now lets load dataset and see the values

In [4]:
dataset = pd.read_csv("/Users/bhavyakansal/Datasets/groceries - groceries.csv")
dataset.head(3)

,Item 1,Item 2,Item 3,Item 4,Item 5,Item 6,Item 7,Item 8,Item 9,Item 10,Item 11
0,citrus fruit,semi-finished bread,margarine,ready soups,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,tropical fruit,yogurt,coffee,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,whole milk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## As we can see we have most NAN values so we have to fill them up as str because we dont have numerical data and we can't fill it with mode or median so we will check the value of nan thats float and then use a List of List and all .

In [5]:
dataset.columns

Index(['Item 1', 'Item 2', 'Item 3', 'Item 4', 'Item 5', 'Item 6', 'Item 7',
       'Item 8', 'Item 9', 'Item 10', 'Item 11'],
      dtype='str')

In [8]:
type(dataset["Item 5"][0])

float

In [10]:
dataset.shape

(9835, 11)

In [23]:
market=[]
for i in range (0 ,dataset.shape[0]):
    customer =[]
    for j in dataset.columns:
        if type(dataset[j][i])== str :
            customer.append(dataset[j][i])
    market.append(customer)

## Now lets find out the most selling or bought Item

In [25]:
import collections

#### Now in collection we have counter variable which help us counting the number of item comes in the dataset but the problem is that it accept single list but as we can see that we have market as list of list means [['citrus fruit', 'semi-finished bread', 'margarine', 'ready soups'],['tropical fruit', 'yogurt', 'coffee'] .... and so on so we first have to convert this into single list using Numpy and then pass it in counters .

In [34]:
list = []
for i in market : 
    for j in i :
        list.append(j)

In [38]:
P = collections.Counter(list)

In [45]:
P.values()

dict_values([814, 163, 550, 16, 1032, 1367, 535, 2513, 744, 382, 38, 1903, 101, 316, 544, 64, 25, 1787, 328, 752, 75, 148, 50, 401, 1041, 416, 521, 162, 161, 516, 580, 1634, 422, 318, 630, 717, 128, 241, 275, 854, 161, 158, 1072, 104, 81, 327, 333, 253, 23, 749, 924, 625, 876, 254, 327, 46, 266, 426, 567, 327, 702, 29, 220, 365, 67, 609, 109, 264, 238, 212, 256, 80, 157, 162, 255, 196, 73, 244, 462, 130, 121, 49, 173, 78, 32, 266, 77, 95, 52, 99, 269, 97, 305, 160, 184, 41, 85, 235, 137, 47, 97, 29, 43, 71, 163, 13, 46, 61, 112, 28, 18, 82, 64, 18, 80, 19, 8, 40, 48, 84, 254, 35, 106, 58, 26, 108, 90, 62, 41, 108, 8, 51, 60, 23, 11, 69, 94, 88, 6, 21, 28, 50, 27, 14, 26, 47, 6, 35, 29, 37, 44, 12, 33, 9, 22, 13, 7, 16, 20, 23, 4, 8, 11, 4, 19, 1, 2, 1])

In [46]:
P.keys()

dict_keys(['citrus fruit', 'semi-finished bread', 'margarine', 'ready soups', 'tropical fruit', 'yogurt', 'coffee', 'whole milk', 'pip fruit', 'cream cheese', 'meat spreads', 'other vegetables', 'condensed milk', 'long life bakery product', 'butter', 'rice', 'abrasive cleaner', 'rolls/buns', 'UHT-milk', 'bottled beer', 'liquor (appetizer)', 'potted plants', 'cereals', 'white bread', 'bottled water', 'chocolate', 'curd', 'flour', 'dishes', 'beef', 'frankfurter', 'soda', 'chicken', 'sugar', 'fruit/vegetable juice', 'newspapers', 'packaged fruit/vegetables', 'specialty bar', 'butter milk', 'pastry', 'processed cheese', 'detergent', 'root vegetables', 'frozen dessert', 'sweet spreads', 'salty snack', 'waffles', 'candy', 'bathroom cleaner', 'canned beer', 'sausage', 'brown bread', 'shopping bags', 'beverages', 'hamburger meat', 'spices', 'hygiene articles', 'napkins', 'pork', 'berries', 'whipped/sour cream', 'artif. sweetener', 'grapes', 'dessert', 'zwieback', 'domestic eggs', 'spread cheese', 'misc. beverages', 'hard cheese', 'cat food', 'ham', 'turkey', 'baking powder', 'pickled vegetables', 'oil', 'chewing gum', 'chocolate marshmallow', 'ice cream', 'frozen vegetables', 'canned fish', 'seasonal products', 'curd cheese', 'red/blush wine', 'frozen potato products', 'specialty fat', 'specialty chocolate', 'candles', 'flower (seeds)', 'sparkling wine', 'salt', 'frozen meals', 'canned vegetables', 'onions', 'herbs', 'white wine', 'brandy', 'photo/film', 'sliced cheese', 'pasta', 'softener', 'cling film/bags', 'fish', 'male cosmetics', 'Instant food products', 'soft cheese', 'honey', 'dental care', 'popcorn', 'cake bar', 'snack products', 'flower soil/fertilizer', 'specialty cheese', 'finished products', 'cocoa drinks', 'dog food', 'prosecco', 'make up remover', 'cleaner', 'female sanitary products', 'dish cleaner', 'meat', 'tea', 'mustard', 'house keeping products', 'potato products', 'liquor', 'pet care', 'soups', 'rum', 'frozen fish', 'salad dressing', 'sauces', 'vinegar', 'soap', 'hair spray', 'instant coffee', 'roll products', 'mayonnaise', 'rubbing alcohol', 'cookware', 'syrup', 'liver loaf', 'canned fruit', 'organic products', 'nut snack', 'kitchen towels', 'frozen chicken', 'light bulbs', 'skin care', 'ketchup', 'jam', 'decalcifier', 'nuts/prunes', 'liqueur', 'organic sausage', 'cream', 'toilet cleaner', 'specialty vegetables', 'pudding powder', 'tidbits', 'baby cosmetics', 'whisky', 'frozen fruits', 'bags', 'cooking chocolate', 'sound storage medium', 'kitchen utensil', 'preservation products'])

## Now we got all value and countings but we have to make it into a simple Dataframe so that we can easily understand and observe that how many items bought how many times and so on .

In [55]:
Dictionary = {"Item_Name" :P.keys() , "Repeation" : P.values() }

In [70]:
pd.set_option("display.max_rows" , 150)
pd.DataFrame(Dictionary).sort_values(by = ["Repeation"] , ascending=False)

                 Item_Name  Repeation
7               whole milk       2513
11        other vegetables       1903
17              rolls/buns       1787
31                    soda       1634
5                   yogurt       1367
..                     ...        ...
160         baby cosmetics          4
163                   bags          4
166        kitchen utensil          2
165   sound storage medium          1
167  preservation products          1

[168 rows x 2 columns]

### Now from here we will going to use our Apriori Algorithm as we have most selling and other infomation . But we cant find this algorithm in sklearn , this algo is used under mlxtend library . 
### Also we can't use this algorithm directly on this dataset. We should have to make a specific matrix in which customers associated or bought that product True or False is included. 
### just like that we done below :

In [72]:
from mlxtend.preprocessing.transactionencoder import TransactionEncoder

In [79]:
tr = TransactionEncoder()
tr.fit(market)

TransactionEncoder()

In [83]:
df = pd.DataFrame(tr.transform(market) , columns=tr.columns_)

In [87]:
df

,Instant food products,UHT-milk,abrasive cleaner,artif. sweetener,baby cosmetics,bags,baking powder,bathroom cleaner,beef,berries,...,turkey,vinegar,waffles,whipped/sour cream,whisky,white bread,white wine,whole milk,yogurt,zwieback
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9830,False,False,False,False,False,False,False,False,True,False,...,False,False,False,True,False,False,False,True,False,False
9831,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9832,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
9833,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9834,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False

### Now lets start implementing Apriori algorithm

In [88]:
from mlxtend.frequent_patterns import apriori

In [94]:
apriori(df , min_support=0.05 , use_colnames=True).sort_values(by = ["support"])

     support                                   itemsets
0   0.052466                          frozenset({beef})
8   0.052974                          frozenset({curd})
7   0.054398                        frozenset({coffee})
28  0.054906        frozenset({rolls/buns, whole milk})
4   0.055313                        frozenset({butter})
29  0.055618            frozenset({whole milk, yogurt})
12  0.055923                     frozenset({margarine})
17  0.057651                          frozenset({pork})
10  0.058973                   frozenset({frankfurter})
9   0.061922                 frozenset({domestic eggs})
3   0.063549                   frozenset({brown bread})
11  0.064057         frozenset({fruit/vegetable juice})
24  0.071378            frozenset({whipped/sour cream})
13  0.072903                    frozenset({newspapers})
27  0.074835  frozenset({other vegetables, whole milk})
16  0.075648                     frozenset({pip fruit})
5   0.076157                   frozenset({canned beer})
1   0.076462                  frozenset({bottled beer})
6   0.082766                  frozenset({citrus fruit})
15  0.086833                        frozenset({pastry})
21  0.089070                 frozenset({shopping bags})
20  0.093950                       frozenset({sausage})
23  0.104931                frozenset({tropical fruit})
2   0.105846                 frozenset({bottled water})
19  0.108998               frozenset({root vegetables})
26  0.138993                        frozenset({yogurt})
22  0.166141                          frozenset({soda})
18  0.181698                    frozenset({rolls/buns})
14  0.193493              frozenset({other vegetables})
25  0.255516                    frozenset({whole milk})

### In above dataset we can clearly see that whole milk is most selling but we can see pairs are made only three i.e : ({rolls/buns, whole milk}) , frozenset({whole milk, yogurt}) , frozenset({other vegetables, whole milk} all others are mostly single and also from these three (other vegetable , whole milk) is most selling with each other so we will consider that further