#### * The FP-Growth (Frequent Pattern Growth) algorithm efficiently mines frequent itemsets from large transactional datasets. Unlike the Apriori algorithm which suffers from high computational cost due to candidate generation and multiple database scans. FP-Growth avoids these inefficiencies by compressing the data into an FP-Tree (Frequent Pattern Tree) and extracts patterns directly from it.

#### * How FP-Growth Works
#### Here's how it works in simple terms:
#### 1. Data Compression: First FP-Growth compresses the dataset into a smaller structure called the Frequent Pattern Tree (FP-Tree). This tree stores information about item sets (collections of items) and their frequencies without need to generate candidate sets like Apriori does.
#### 2. Mining the Tree: The algorithm then examines this tree to identify patterns that appear frequently based on a minimum support threshold. It does this by breaking the tree down into smaller "conditional" trees for each item making the process more efficient.
#### 3. Generating Patterns: Once the tree is built and analyzed the algorithm generates the frequent patterns (itemsets) and the rules that describe relationships between items.

#### * Why FP-Growth is Efficient

#### It scans the database only twice.
#### It avoids generating all combinations of items.
#### It stores data in a compact tree, reducing redundancy.
#### It uses conditional trees to mine deeper patterns efficiently.

### Now lets import basic libraries first

In [2]:
import pandas as pd

In [4]:
pd.set_option("display.max_rows" , 500)

In [5]:
dataset = pd.read_csv("/Users/bhavyakansal/Datasets/groceries - groceries.csv")
dataset.head(3)

,Item 1,Item 2,Item 3,Item 4,Item 5,Item 6,Item 7,Item 8,Item 9,Item 10,Item 11
0,citrus fruit,semi-finished bread,margarine,ready soups,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,tropical fruit,yogurt,coffee,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,whole milk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
dataset.shape

(9835, 11)

In [7]:
market=[]
for i in range (0 ,dataset.shape[0]):
    customer =[]
    for j in dataset.columns:
        if type(dataset[j][i])== str :
            customer.append(dataset[j][i])
    market.append(customer)

In [8]:
list = []
for i in market : 
    for j in i :
        list.append(j)

### Now in collection we have counter variable which help us counting the number of item comes in the dataset but the problem is that it accept single list but as we can see that we have market as list of list means [['citrus fruit', 'semi-finished bread', 'margarine', 'ready soups'],['tropical fruit', 'yogurt', 'coffee'] .... and so on so we first have to convert this into single list using Numpy and then pass it in counters .¶

In [10]:
import collections

In [11]:
P = collections.Counter(list)
P.values()

dict_values([814, 163, 550, 16, 1032, 1367, 535, 2513, 744, 382, 38, 1903, 101, 316, 544, 64, 25, 1787, 328, 752, 75, 148, 50, 401, 1041, 416, 521, 162, 161, 516, 580, 1634, 422, 318, 630, 717, 128, 241, 275, 854, 161, 158, 1072, 104, 81, 327, 333, 253, 23, 749, 924, 625, 876, 254, 327, 46, 266, 426, 567, 327, 702, 29, 220, 365, 67, 609, 109, 264, 238, 212, 256, 80, 157, 162, 255, 196, 73, 244, 462, 130, 121, 49, 173, 78, 32, 266, 77, 95, 52, 99, 269, 97, 305, 160, 184, 41, 85, 235, 137, 47, 97, 29, 43, 71, 163, 13, 46, 61, 112, 28, 18, 82, 64, 18, 80, 19, 8, 40, 48, 84, 254, 35, 106, 58, 26, 108, 90, 62, 41, 108, 8, 51, 60, 23, 11, 69, 94, 88, 6, 21, 28, 50, 27, 14, 26, 47, 6, 35, 29, 37, 44, 12, 33, 9, 22, 13, 7, 16, 20, 23, 4, 8, 11, 4, 19, 1, 2, 1])

In [12]:
P.keys()

dict_keys(['citrus fruit', 'semi-finished bread', 'margarine', 'ready soups', 'tropical fruit', 'yogurt', 'coffee', 'whole milk', 'pip fruit', 'cream cheese', 'meat spreads', 'other vegetables', 'condensed milk', 'long life bakery product', 'butter', 'rice', 'abrasive cleaner', 'rolls/buns', 'UHT-milk', 'bottled beer', 'liquor (appetizer)', 'potted plants', 'cereals', 'white bread', 'bottled water', 'chocolate', 'curd', 'flour', 'dishes', 'beef', 'frankfurter', 'soda', 'chicken', 'sugar', 'fruit/vegetable juice', 'newspapers', 'packaged fruit/vegetables', 'specialty bar', 'butter milk', 'pastry', 'processed cheese', 'detergent', 'root vegetables', 'frozen dessert', 'sweet spreads', 'salty snack', 'waffles', 'candy', 'bathroom cleaner', 'canned beer', 'sausage', 'brown bread', 'shopping bags', 'beverages', 'hamburger meat', 'spices', 'hygiene articles', 'napkins', 'pork', 'berries', 'whipped/sour cream', 'artif. sweetener', 'grapes', 'dessert', 'zwieback', 'domestic eggs', 'spread cheese', 'misc. beverages', 'hard cheese', 'cat food', 'ham', 'turkey', 'baking powder', 'pickled vegetables', 'oil', 'chewing gum', 'chocolate marshmallow', 'ice cream', 'frozen vegetables', 'canned fish', 'seasonal products', 'curd cheese', 'red/blush wine', 'frozen potato products', 'specialty fat', 'specialty chocolate', 'candles', 'flower (seeds)', 'sparkling wine', 'salt', 'frozen meals', 'canned vegetables', 'onions', 'herbs', 'white wine', 'brandy', 'photo/film', 'sliced cheese', 'pasta', 'softener', 'cling film/bags', 'fish', 'male cosmetics', 'Instant food products', 'soft cheese', 'honey', 'dental care', 'popcorn', 'cake bar', 'snack products', 'flower soil/fertilizer', 'specialty cheese', 'finished products', 'cocoa drinks', 'dog food', 'prosecco', 'make up remover', 'cleaner', 'female sanitary products', 'dish cleaner', 'meat', 'tea', 'mustard', 'house keeping products', 'potato products', 'liquor', 'pet care', 'soups', 'rum', 'frozen fish', 'salad dressing', 'sauces', 'vinegar', 'soap', 'hair spray', 'instant coffee', 'roll products', 'mayonnaise', 'rubbing alcohol', 'cookware', 'syrup', 'liver loaf', 'canned fruit', 'organic products', 'nut snack', 'kitchen towels', 'frozen chicken', 'light bulbs', 'skin care', 'ketchup', 'jam', 'decalcifier', 'nuts/prunes', 'liqueur', 'organic sausage', 'cream', 'toilet cleaner', 'specialty vegetables', 'pudding powder', 'tidbits', 'baby cosmetics', 'whisky', 'frozen fruits', 'bags', 'cooking chocolate', 'sound storage medium', 'kitchen utensil', 'preservation products'])

In [13]:
Dictionary = {"Item_Name" :P.keys() , "Repeation" : P.values() }

In [14]:
pd.DataFrame(Dictionary).sort_values(by = ["Repeation"] , ascending=False)

                     Item_Name  Repeation
7                   whole milk       2513
11            other vegetables       1903
17                  rolls/buns       1787
31                        soda       1634
5                       yogurt       1367
42             root vegetables       1072
24               bottled water       1041
4               tropical fruit       1032
50                     sausage        924
52               shopping bags        876
39                      pastry        854
0                 citrus fruit        814
19                bottled beer        752
49                 canned beer        749
8                    pip fruit        744
35                  newspapers        717
60          whipped/sour cream        702
34       fruit/vegetable juice        630
51                 brown bread        625
65               domestic eggs        609
30                 frankfurter        580
58                        pork        567
2                    margarine        550
14                      butter        544
6                       coffee        535
26                        curd        521
29                        beef        516
78           frozen vegetables        462
57                     napkins        426
32                     chicken        422
25                   chocolate        416
23                 white bread        401
9                 cream cheese        382
63                     dessert        365
46                     waffles        333
18                    UHT-milk        328
45                 salty snack        327
54              hamburger meat        327
59                     berries        327
33                       sugar        318
13    long life bakery product        316
92                      onions        305
38                 butter milk        275
90                frozen meals        269
85         specialty chocolate        266
56            hygiene articles        266
67             misc. beverages        264
70                         ham        256
74                         oil        255
53                   beverages        254
120                       meat        254
47                       candy        253
77                   ice cream        244
37               specialty bar        241
68                 hard cheese        238
97               sliced cheese        235
62                      grapes        220
69                    cat food        212
75                 chewing gum        196
94                  white wine        184
82              red/blush wine        173
104                soft cheese        163
1          semi-finished bread        163
27                       flour        162
73          pickled vegetables        162
40            processed cheese        161
28                      dishes        161
93                       herbs        160
41                   detergent        158
72               baking powder        157
21               potted plants        148
98                       pasta        137
79                 canned fish        130
36   packaged fruit/vegetables        128
80           seasonal products        121
108                   cake bar        112
66               spread cheese        109
125                     liquor        108
129                frozen fish        108
122                    mustard        106
43              frozen dessert        104
12              condensed milk        101
89                        salt         99
91           canned vegetables         97
100            cling film/bags         97
87              flower (seeds)         95
136              roll products         94
126                   pet care         90
137                 mayonnaise         88
96                  photo/film         85
119               dish cleaner         84
111           specialty cheese         82
44               sweet spreads         81
71                      turkey         80
114                   dog food         80
83      frozen potato products         78
86                     candles         77
20          liquor (appetizer)         75
76       chocolate marshmallow         73
103      Instant food products         71
135             instant coffee         69
64                    zwieback         67
15                        rice         64
112          finished products         64
127                      soups         62
107                    popcorn         61
132                    vinegar         60
123     house keeping products         58
88              sparkling wine         52
131                     sauces         51
22                     cereals         50
141                 liver loaf         50
81                 curd cheese         49
118   female sanitary products         48
99                    softener         47
145             kitchen towels         47
106                dental care         46
55                      spices         46
150                        jam         44
102             male cosmetics         43
95                      brandy         41
128                        rum         41
117                    cleaner         40
10                meat spreads         38
149                    ketchup         37
121                        tea         35
147                light bulbs         35
152                nuts/prunes         33
84               specialty fat         32
148                  skin care         29
61            artif. sweetener         29
101                       fish         29
109             snack products         28
140                      syrup         28
142               canned fruit         27
144                  nut snack         26
124            potato products         26
16            abrasive cleaner         25
48            bathroom cleaner         23
159                    tidbits         23
133                       soap         23
154            organic sausage         22
139                   cookware         21
158             pudding powder         20
164          cooking chocolate         19
115                   prosecco         19
110     flower soil/fertilizer         18
113               cocoa drinks         18
157       specialty vegetables         16
3                  ready soups         16
143           organic products         14
105                      honey         13
155                      cream         13
151                decalcifier         12
134                 hair spray         11
162              frozen fruits         11
153                    liqueur          9
161                     whisky          8
130             salad dressing          8
116            make up remover          8
156             toilet cleaner          7
146             frozen chicken          6
138            rubbing alcohol          6
160             baby cosmetics          4
163                       bags          4
166            kitchen utensil          2
165       sound storage medium          1
167      preservation products          1

In [15]:
from mlxtend.preprocessing.transactionencoder import TransactionEncoder

In [19]:
tr = TransactionEncoder()
tr.fit(market)

TransactionEncoder()

In [20]:
df = pd.DataFrame(tr.transform(market) , columns=tr.columns_)

In [21]:
df

,Instant food products,UHT-milk,abrasive cleaner,artif. sweetener,baby cosmetics,bags,baking powder,bathroom cleaner,beef,berries,...,turkey,vinegar,waffles,whipped/sour cream,whisky,white bread,white wine,whole milk,yogurt,zwieback
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9830,False,False,False,False,False,False,False,False,True,False,...,False,False,False,True,False,False,False,True,False,False
9831,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9832,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
9833,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9834,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False

### Now lets start implementing FP Growth Algorithm

In [22]:
from mlxtend.frequent_patterns import fpgrowth

In [24]:
fpgrowth(df , min_support= 0.07 , use_colnames=True , max_len= 3).sort_values( by =["support"])

     support                                   itemsets
16  0.071378            frozenset({whipped/sour cream})
10  0.072903                    frozenset({newspapers})
17  0.074835  frozenset({other vegetables, whole milk})
4   0.075648                     frozenset({pip fruit})
13  0.076157                   frozenset({canned beer})
7   0.076462                  frozenset({bottled beer})
0   0.082766                  frozenset({citrus fruit})
11  0.086833                        frozenset({pastry})
15  0.089070                 frozenset({shopping bags})
14  0.093950                       frozenset({sausage})
2   0.104931                frozenset({tropical fruit})
8   0.105846                 frozenset({bottled water})
12  0.108998               frozenset({root vegetables})
1   0.138993                        frozenset({yogurt})
9   0.166141                          frozenset({soda})
6   0.181698                    frozenset({rolls/buns})
5   0.193493              frozenset({other vegetables})
3   0.255516                    frozenset({whole milk})

### Now as we can see in 0.07 support we only get frozenset({other vegetables, whole milk}) as pair rest others are single or too low so we consider this further if we do ..